<?php
/**
 * @file
 * Backdrop hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_multiple_entities_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_multiple_entities_alter_settings'] = array(
    'name' => t('File attachments Multiple Entities'),
    'description' => t('Extract the content of attached files of multiple entities in the index and index it.'),
    'class' => 'SearchApiAttachmentsMultipleEntitiesAlterSettings',
  );
  return $callbacks;
}

/**
 * Implements hook_autoload_info().
 */
function search_api_attachments_multiple_entities_autoload_info() {
  return array(
    'SearchApiAttachmentsMultipleEntitiesAlterSettings' => 'includes/callback_attachments_multiple_entities_settings.inc',
  );
}
